language: objective-c
before_install:
  - gem install xcpretty -N
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -project 'CCHLinkTextView Example/CCHLinkTextView Example.xcodeproj' -scheme 'CCHLinkTextView Example' -sdk iphonesimulator -configuration Debug test | xcpretty -c
