language: objective-c
before_install:
  - gem install xcpretty
script: 
  - xcodebuild -project 'CCHLinkTextView Example/CCHLinkTextView Example.xcodeproj' -scheme 'CCHLinkTextView Example' -sdk iphonesimulator -configuration Debug test | xcpretty -c; exit ${PIPESTATUS[0]}
